### PR TITLE
adding option to make statistics calculations optional

### PR DESCRIPTION
**Pull request by yawetse**
some of the stat calculations are stuck in an infinite loop. I'll make a separate issue for that, but it would be nice to make the calculation of statistics optional.

### CODE REVIEW

**Comment by yawetse** [comment]
hi @krwes @targos do you mind taking a look at this PR?

thanks!

**Comment by targos** [comment]
Sorry, I missed the first notification on this PR. The change looks good to me, thanks! Can you please add a reference to the new option in the README?

**Comment by yawetse** [comment]
@targos absolutely! I just updated the README. Thanks!

**Comment by targos** [comment]
Published in 1.2.0. Thanks again for the contribution!

**Pull request merged**
